books = [
    {
        "id": "1",
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_year": 2008,
        "language": "English",
        "pages": 464,
    },
    {
        "id": "2",
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt, David Thomas",
        "publisher": "Addison-Wesley",
        "published_year": 1999,
        "language": "English",
        "pages": 352,
    },
    {
        "id": "3",
        "title": "Introduction to Algorithms",
        "author": "Thomas H. Cormen",
        "publisher": "MIT Press",
        "published_year": 2009,
        "language": "English",
        "pages": 1312,
    },
    {
        "id": "4",
        "title": "Design Patterns",
        "author": "Erich Gamma et al.",
        "publisher": "Addison-Wesley",
        "published_year": 1994,
        "language": "English",
        "pages": 395,
    },
    {
        "id": "5",
        "title": "You Don't Know JS",
        "author": "Kyle Simpson",
        "publisher": "O'Reilly Media",
        "published_year": 2015,
        "language": "English",
        "pages": 278,
    },
]
